name: Lee Vienup
favicon: null
layout_spectrum: 0.4621124919503927
typography_spectrum: 0.3839618058409542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.17345634778030217
  lightness: 0.4977903803810477
  saturation: 0.118897964945063
  rhythmicContrast: 0.7342564866412431
purpose: []
